version: '3.8'

services:
  php-fpm:
    image: php-fpm-pr
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
